# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Deepansha Wadhera'
tagline:          ': Life Is Learning!'
description:      'Programmer · Developer · Learner'
url:              //aktech.github.io

author:
  name:           'Deepansha Wadhera'
  email:          deepansha.wadhera2@gmail.com

# contact details
contact:
  github:         https://github.com/deepanshaW
  gmail:          mailto:deepansha.wadhera2@gmail.com

# Gems

source:      .
destination: ./_site

timezone: Asia/Calcutta

devurl: http://localhost:4000
port: 4000
host: 0.0.0.0
baseurl: /
theme: jekyll-theme-cayman